/* ========================  DATA  ======================== */
const pluginsBase = [
    { id:1, nameZh:"月影咖啡馆", nameEn:"Moonlit Café", devZh:"月影咖啡", devEn:"Moonlit Coffee", cat:"brand", statusZh:"已完成", statusEn:"Completed", reviewsZh:"3个月", reviewsEn:"3 mo", users:"2025", icon:"fas fa-moon", iconBg:"#3d3d3d", url:"#", descZh:"为独立精品咖啡馆打造的全套品牌识别系统。从标志设计到空间视觉，以月影与咖啡香气的意象贯穿始终。", descEn:"A complete brand identity system for an independent boutique café. From logo design to spatial visuals, the imagery of moonlight and coffee aroma runs throughout." },
    { id:2, nameZh:"东方瓷韵", nameEn:"Oriental Porcelain", devZh:"东方瓷艺", devEn:"Oriental Ceramics", cat:"product", statusZh:"已入土", statusEn:"Buried", reviewsZh:"4个月", reviewsEn:"4 mo", users:"2024", icon:"fas fa-wine-glass-alt", iconBg:"#c4a882", url:"#", descZh:"传统陶瓷工艺的当代产品化探索。通过极简造型与釉色实验，让千年瓷文化融入现代生活场景。", descEn:"A contemporary product exploration of traditional ceramic craftsmanship. Through minimalist forms and glaze experiments, millennia-old porcelain culture merges into modern living." },
    { id:3, nameZh:"城市漫游者", nameEn:"Urban Wanderer", devZh:"城市实验室", devEn:"Urban Lab", cat:"digital", statusZh:"迭代中", statusEn:"Iterating", reviewsZh:"2个月", reviewsEn:"2 mo", users:"2025", icon:"fas fa-compass", iconBg:"#5a7d8c", url:"#", descZh:"城市探索类移动应用的概念设计。以地图为画布，用足迹连接城市中隐秘的角落与故事。", descEn:"Concept design for a city exploration mobile app. Using the map as a canvas, footprints connect hidden corners and stories across the city." },
    { id:4, nameZh:"静谧花园", nameEn:"Silent Garden", devZh:"静谧出版", devEn:"Silent Press", cat:"editorial", statusZh:"已入土", statusEn:"Buried", reviewsZh:"3个月", reviewsEn:"3 mo", users:"2023", icon:"fas fa-leaf", iconBg:"#7a9e7e", url:"#", descZh:"一本关于植物与内心平静的独立杂志。版式设计以大量留白呼应花园的空灵与静谧。", descEn:"An independent magazine about plants and inner peace. The typography uses generous white space to echo the ethereal quietness of a garden." },
    { id:5, nameZh:"未来叙事", nameEn:"Future Narrative", devZh:"未来科技", devEn:"Future Tech", cat:"brand", statusZh:"进行中", statusEn:"In Progress", reviewsZh:"4个月", reviewsEn:"4 mo", users:"2025", icon:"fas fa-atom", iconBg:"#4a5568", url:"#", descZh:"科技文化品牌的视觉体系构建。以动态粒子与几何语言，呈现人类与技术的共生关系。", descEn:"Visual system construction for a tech culture brand. Using dynamic particles and geometric language to present the symbiotic relationship between humanity and technology." },
    { id:6, nameZh:"纸间诗意", nameEn:"Paper Poetry", devZh:"纸间工坊", devEn:"Paper Studio", cat:"editorial", statusZh:"已完成", statusEn:"Completed", reviewsZh:"2个月", reviewsEn:"2 mo", users:"2024", icon:"fas fa-book-open", iconBg:"#b8a99a", url:"#", descZh:"手工书籍装帧与排版的艺术实践。每一页都是纸张与文字之间的对话，触感与视觉并重。", descEn:"An artistic practice of handmade bookbinding and typography. Every page is a dialogue between paper and text, with equal weight on tactile and visual experience." },
    { id:7, nameZh:"深海之声", nameEn:"Deep Sea Voice", devZh:"海洋保护", devEn:"Ocean Conservation", cat:"digital", statusZh:"已完成", statusEn:"Completed", reviewsZh:"5个月", reviewsEn:"5 mo", users:"2025", icon:"fas fa-water", iconBg:"#4a7c8c", url:"#", descZh:"海洋生态保护主题的数字互动装置。用户可以通过手势探索虚拟深海，聆听鲸鱼的歌声。", descEn:"A digital interactive installation themed on ocean conservation. Users can explore a virtual deep sea through gestures and listen to whale songs." },
    { id:8, nameZh:"原木生活", nameEn:"Raw Wood Living", devZh:"原木工坊", devEn:"Raw Wood Studio", cat:"product", statusZh:"已完成", statusEn:"Completed", reviewsZh:"4个月", reviewsEn:"4 mo", users:"2024", icon:"fas fa-tree", iconBg:"#8b7355", url:"#", descZh:"可持续家具系列产品设计。保留木材的天然肌理与缺陷，让每一件家具都拥有独一无二的性格。", descEn:"Sustainable furniture series design. Preserving the natural grain and imperfections of wood, each piece of furniture possesses a unique character." },
    { id:9, nameZh:"光影剧场", nameEn:"Light Shadow Theater", devZh:"光影剧团", devEn:"Light Shadow Troupe", cat:"brand", statusZh:"已入土", statusEn:"Buried", reviewsZh:"3个月", reviewsEn:"3 mo", users:"2023", icon:"fas fa-theater-masks", iconBg:"#2d2d2d", url:"#", descZh:"独立剧场的品牌重塑项目。以光影为设计语言，重新定义表演艺术机构的文化身份。", descEn:"A brand redesign project for an independent theater. Using light and shadow as design language, redefining the cultural identity of a performing arts institution." },
    { id:10, nameZh:"像素记忆", nameEn:"Pixel Memory", devZh:"记忆存档", devEn:"Memory Archive", cat:"digital", statusZh:"迭代中", statusEn:"Iterating", reviewsZh:"3个月", reviewsEn:"3 mo", users:"2025", icon:"fas fa-memory", iconBg:"#6b7b8c", url:"#", descZh:"数字遗产存档平台的界面设计。帮助用户整理、保存和分享跨越数十年的数字生活片段。", descEn:"Interface design for a digital legacy archiving platform. Helping users organize, preserve, and share digital life fragments spanning decades." },
    { id:11, nameZh:"丝绸之路", nameEn:"Silk Road", devZh:"丝路文化", devEn:"Silk Road Culture", cat:"editorial", statusZh:"已入土", statusEn:"Buried", reviewsZh:"4个月", reviewsEn:"4 mo", users:"2024", icon:"fas fa-route", iconBg:"#b8860b", url:"#", descZh:"丝绸之路文化主题的视觉出版物。融合历史文献与现代设计手法，讲述跨越时空的贸易与文化交流。", descEn:"A visual publication themed on Silk Road culture. Blending historical documents with modern design techniques to tell stories of trade and cultural exchange across time and space." },
    { id:12, nameZh:"极简主义", nameEn:"Minimalist Manifesto", devZh:"减法生活", devEn:"Subtractive Living", cat:"brand", statusZh:"已完成", statusEn:"Completed", reviewsZh:"2个月", reviewsEn:"2 mo", users:"2025", icon:"fas fa-minus", iconBg:"#999999", url:"#", descZh:"一个倡导减法生活的品牌全案。用最克制的视觉语言，传递最丰富的生活哲学。", descEn:"A complete brand case advocating subtractive living. Using the most restrained visual language to convey the richest life philosophy." },
    { id:13, nameZh:"数字荒野", nameEn:"Digital Wilderness", devZh:"荒野科技", devEn:"Wilderness Tech", cat:"digital", statusZh:"进行中", statusEn:"In Progress", reviewsZh:"5个月", reviewsEn:"5 mo", users:"2024", icon:"fas fa-vr-cardboard", iconBg:"#5c7c5c", url:"#", descZh:"虚拟现实自然体验项目的交互设计。在数字世界中重建一片荒野，让城市人重新感受自然的力量。", descEn:"Interaction design for a VR nature experience project. Reconstructing a wilderness in the digital world, allowing urban dwellers to reconnect with the power of nature." },
    { id:14, nameZh:"手工温度", nameEn:"Handmade Warmth", devZh:"匠心皮具", devEn:"Craft Leather", cat:"product", statusZh:"已入土", statusEn:"Buried", reviewsZh:"3个月", reviewsEn:"3 mo", users:"2023", icon:"fas fa-hand-holding-heart", iconBg:"#a0785a", url:"#", descZh:"手工皮具品牌的系列产品设计。从选材到缝线的每一个细节，都在讲述匠人的专注与温度。", descEn:"Product series design for a handmade leather goods brand. From material selection to stitching, every detail tells the story of the craftsman's focus and warmth." },
    { id:15, nameZh:"超现实梦境", nameEn:"Surreal Dreams", devZh:"梦境画廊", devEn:"Dream Gallery", cat:"editorial", statusZh:"已完成", statusEn:"Completed", reviewsZh:"4个月", reviewsEn:"4 mo", users:"2025", icon:"fas fa-cloud-moon", iconBg:"#7a6b8c", url:"#", descZh:"当代艺术展览的展陈与出版物设计。将超现实主义画作转化为三维空间的沉浸式阅读体验。", descEn:"Exhibition curation and publication design for a contemporary art show. Transforming surrealist paintings into an immersive three-dimensional reading experience." },
    { id:16, nameZh:"品牌重塑", nameEn:"Brand Rebirth", devZh:"百年老店", devEn:"Century Shop", cat:"brand", statusZh:"已入土", statusEn:"Buried", reviewsZh:"6个月", reviewsEn:"6 mo", users:"2024", icon:"fas fa-sync-alt", iconBg:"#6b6b6b", url:"#", descZh:"百年老字号的现代化品牌升级。在保留历史基因的同时，注入当代设计语言与年轻活力。", descEn:"A modern brand upgrade for a century-old heritage brand. Injecting contemporary design language and youthful energy while preserving its historical DNA." },
    { id:17, nameZh:"虚拟空间", nameEn:"Virtual Space", devZh:"线上画廊", devEn:"Online Gallery", cat:"digital", statusZh:"进行中", statusEn:"In Progress", reviewsZh:"4个月", reviewsEn:"4 mo", users:"2025", icon:"fas fa-cube", iconBg:"#5a6b7c", url:"#", descZh:"线上画廊的三维虚拟空间设计。观众可以自由漫游，近距离欣赏每一幅艺术作品的细节。", descEn:"3D virtual space design for an online gallery. Visitors can freely roam and examine the details of every artwork up close." },
    { id:18, nameZh:"植物图鉴", nameEn:"Plant Atlas", devZh:"植物科普", devEn:"Botany Edu", cat:"product", statusZh:"已完成", statusEn:"Completed", reviewsZh:"3个月", reviewsEn:"3 mo", users:"2024", icon:"fas fa-seedling", iconBg:"#6b8c5a", url:"#", descZh:"植物科普产品的视觉系统设计。将复杂的植物学知识转化为直观的图形语言与交互体验。", descEn:"Visual system design for a botanical education product. Transforming complex botanical knowledge into intuitive graphic language and interactive experience." },
    { id:19, nameZh:"时间碎片", nameEn:"Time Fragments", devZh:"时间实验", devEn:"Time Lab", cat:"editorial", statusZh:"已完成", statusEn:"Completed", reviewsZh:"2个月", reviewsEn:"2 mo", users:"2023", icon:"fas fa-hourglass-half", iconBg:"#8c8c8c", url:"#", descZh:"一本关于时间感知的设计实验出版物。通过非线性排版与特殊纸张，探索时间的多重维度。", descEn:"A design experiment publication about the perception of time. Through nonlinear typography and special paper stocks, exploring the multiple dimensions of time." },
    { id:20, nameZh:"纯粹几何", nameEn:"Pure Geometry", devZh:"几何建筑", devEn:"Geometry Arch", cat:"brand", statusZh:"已完成", statusEn:"Completed", reviewsZh:"4个月", reviewsEn:"4 mo", users:"2025", icon:"fas fa-shapes", iconBg:"#7a7a7a", url:"#", descZh:"建筑事务所的品牌识别系统。以最基本的几何形态为起点，构建理性与诗意并存的视觉语言。", descEn:"Brand identity system for an architecture firm. Starting from the most basic geometric forms, building a visual language where rationality and poetry coexist." },
    { id:21, nameZh:"数据可视化", nameEn:"Data Visualization", devZh:"气候数据", devEn:"Climate Data", cat:"digital", statusZh:"迭代中", statusEn:"Iterating", reviewsZh:"5个月", reviewsEn:"5 mo", users:"2024", icon:"fas fa-chart-line", iconBg:"#5c7a8c", url:"#", descZh:"气候数据的公共艺术可视化项目。将抽象的数据转化为可感知的光影与色彩，唤醒环保意识。", descEn:"A public art data visualization project on climate data. Transforming abstract data into perceptible light, shadow, and color to awaken environmental awareness." },
    { id:22, nameZh:"陶器工坊", nameEn:"Pottery Workshop", devZh:"陶艺空间", devEn:"Pottery Space", cat:"product", statusZh:"已入土", statusEn:"Buried", reviewsZh:"4个月", reviewsEn:"4 mo", users:"2023", icon:"fas fa-hands", iconBg:"#a08060", url:"#", descZh:"陶艺工作坊的空间与器具整体设计。从拉坯机到茶杯，每一处细节都服务于双手与泥土的对话。", descEn:"Integrated spatial and tool design for a pottery workshop. From the wheel to the teacup, every detail serves the dialogue between hands and clay." },
    { id:23, nameZh:"城市档案", nameEn:"City Archives", devZh:"城市记忆", devEn:"City Memory", cat:"editorial", statusZh:"已入土", statusEn:"Buried", reviewsZh:"3个月", reviewsEn:"3 mo", users:"2024", icon:"fas fa-building", iconBg:"#8c8c8c", url:"#", descZh:"城市变迁主题的纪录片式出版物。用档案照片与当代设计的对话，记录一座城市的记忆与伤痕。", descEn:"A documentary-style publication about urban transformation. Using a dialogue between archival photographs and contemporary design to record a city's memories and scars." },
    { id:24, nameZh:"感知色彩", nameEn:"Perceived Color", devZh:"色彩心理", devEn:"Color Psychology", cat:"brand", statusZh:"已完成", statusEn:"Completed", reviewsZh:"2个月", reviewsEn:"2 mo", users:"2025", icon:"fas fa-eye", iconBg:"#8c7a6b", url:"#", descZh:"色彩心理学工作室的品牌设计。每一种色彩都被赋予情绪与叙事，帮助品牌找到最真实的表达。", descEn:"Brand design for a color psychology studio. Each color is endowed with emotion and narrative, helping brands find their most authentic expression." }
];

function getPlugins() {
    return pluginsBase.map(p => ({
        ...p,
        displayName: lang === 'zh' ? p.nameZh : p.nameEn,
        desc: lang === 'zh' ? p.descZh : p.descEn,
        dev: lang === 'zh' ? p.devZh : p.devEn,
        status: lang === 'zh' ? p.statusZh : p.statusEn,
        reviews: lang === 'zh' ? p.reviewsZh : p.reviewsEn,
        catLabel: t('catLabels.' + p.cat)
    }));
}

